version: "3.8"

services:
  nextcloud-db:
    image: mariadb:10.6
    container_name: nextcloud-db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      # [UBAH KESINI] Arahkan database ke LVM
      - /srv/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 16G      # Beri MariaDB keleluasaan 16GB RAM

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G       # Redis cukup 4GB untuk cache super cepat

  nextcloud-clamav:
    image: clamav/clamav:latest
    container_name: nextcloud-clamav
    restart: unless-stopped
    environment:
      - CLAMAV_NO_FRESHCLAM=false
    volumes:
      - nextcloud-clamav-db:/var/lib/clamav
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G       # ClamAV butuh minimal 3-4GB saat update database virus

  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: always
    ports:
      # [UBAH KESINI] Kunci port 9977 hanya untuk Nginx lokal (Keamanan)
      - "127.0.0.1:9977:80"
    volumes:
      # [UBAH KESINI] Arahkan file aplikasi dan user ke LVM
      - /srv/nextcloud/data:/var/www/html
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=nextcloud-db
      - REDIS_HOST=nextcloud-redis
      - NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}
      - OVERWRITEPROTOCOL=https
      - OVERWRITEHOST=${NEXTCLOUD_DOMAIN}
      - OVERWRITEWEBROOT=/nextcloud
      - OVERWRITECLIURL=https://${NEXTCLOUD_DOMAIN}/nextcloud
      # [TAMBAHAN] Optimasi PHP untuk server besar
      - PHP_MEMORY_LIMIT=4G
      - PHP_UPLOAD_LIMIT=10G
    env_file:
      - .env
    depends_on:
      - nextcloud-db
      - nextcloud-redis
      - nextcloud-clamav
    deploy:
      resources:
        limits:
          cpus: '16.0'
          memory: 16G      # App Nextcloud maksimal pakai 16GB RAM

volumes:
  nextcloud-clamav-db:
